# Generated by Django 3.2.12 on 2023-04-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True)),
                ('category_l1', models.CharField(max_length=255)),
                ('category_l2', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enable', models.CharField(max_length=3)),
                ('size', models.CharField(max_length=255)),
                ('UPC', models.CharField(max_length=255)),
            ],
        ),
    ]
